# Generated by Django 3.1.2 on 2020-11-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Property',
        ),
    ]
