# Generated by Django 3.1.2 on 2020-11-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20201110_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='type',
            new_name='property_type',
        ),
    ]
