# Generated by Django 3.1.2 on 2021-01-07 13:12

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20210105_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null='51.903614, -8.468399'),
            preserve_default='51.903614, -8.468399',
        ),
        migrations.AddField(
            model_name='property',
            name='google_address',
            field=django_google_maps.fields.AddressField(default=(51.903614, -8.468399), max_length=200),
            preserve_default=False,
        ),
    ]
