# Generated by Django 3.1.2 on 2021-01-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20210107_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='property',
            name='google_address',
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=25, null=True),
        ),
    ]
