# Generated by Django 3.1.2 on 2021-01-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20210108_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=51.89575, max_digits=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=-8.47443, max_digits=25),
            preserve_default=False,
        ),
    ]
