# Generated by Django 3.1.2 on 2021-01-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date_added',
            field=models.DateTimeField(blank=True),
        ),
    ]
