# Generated by Django 3.1.2 on 2021-01-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_auto_20210120_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_facilities',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_features',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rooms_description',
        ),
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='agent',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
