# Generated by Django 3.1.2 on 2021-01-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_auto_20210121_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_url',
        ),
    ]
