# Generated by Django 3.1.2 on 2021-01-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_auto_20210122_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sale_status',
            field=models.CharField(choices=[('For_Sale', 'For Sale'), ('Sale_Agreed', 'Sale Agreed'), ('Sold', 'Sold')], default='For_Sale', max_length=30),
        ),
    ]
