# Generated by Django 3.1.2 on 2021-01-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_property_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='sale_status',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('Sale Agreed', 'Sale Agreed'), ('Sold', 'Sold')], default='For_Sale', max_length=30),
        ),
    ]
