# Generated by Django 3.1.2 on 2021-01-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_auto_20210126_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
