# Generated by Django 3.1.2 on 2021-03-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_auto_20210126_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='size',
        ),
        migrations.AddField(
            model_name='property',
            name='acres',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='if acres leave blank', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sqm',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='if acres leave blank', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=20, help_text="Navigate to Google's Maps, Enter the address you want to find, Right click on the Map's pin point and the lat-lng will appear. Latitude is the first number, longitude is second. eg. (51.89371, -8.49649) (latitude, longitude)", max_digits=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text="Put price as 5000000 if you want 'Price Upon Request'", max_digits=8),
        ),
    ]
