# Generated by Django 3.1.2 on 2021-03-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_auto_20210309_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='acres',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='if sqm leave blank', max_digits=8, null=True),
        ),
    ]
