# Generated by Django 3.1.2 on 2021-03-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_auto_20210309_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='matterport_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='youtube_video',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
