# Generated by Django 3.1.2 on 2021-03-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_auto_20210311_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Requires the id of youtube video Not the full url. Id is the last part of the url eg. https://www.youtube.com/watch?v=ZIOCKqk4x3A the id here is ZIOCKqk4x3A ', max_length=1024, null=True),
        ),
    ]
