# Generated by Django 3.1.2 on 2021-03-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_auto_20210311_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='matterport_link',
        ),
        migrations.AddField(
            model_name='property',
            name='matterport_id',
            field=models.CharField(blank=True, help_text='Requires the ID of matterport video Not the full url. ID is the last part of the url eg. https://my.matterport.com/show/?m=PhqeQDhKBYd the ID here is PhqeQDhKBYd ', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Requires the ID of youtube video Not the full url. ID is the last part of the url eg. https://www.youtube.com/watch?v=ZIOCKqk4x3A the ID here is ZIOCKqk4x3A ', max_length=1024, null=True),
        ),
    ]
