# Generated by Django 3.1.2 on 2021-01-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tesimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_name', models.CharField(max_length=254)),
                ('comment', models.TextField(max_length=350)),
                ('date_published', models.DateField()),
            ],
        ),
    ]
