# Generated by Django 3.1.2 on 2021-01-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tesimonial',
            new_name='Testimonial',
        ),
    ]
